# Generated by Django 4.1.6 on 2023-02-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(max_length=3000, verbose_name='Описание')),
                ('status', models.TextField(max_length=200, verbose_name='Статус')),
                ('author', models.CharField(max_length=200, verbose_name='Автор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время обновления')),
            ],
        ),
    ]
